apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 26.1.0

    # External Names set for gitea
    chart: traefik
    helm:
      valuesObject:
        providers:
          kubernetesCRD:
            allowExternalNameServices: true
        service:
          spec:
            externalTrafficPolicy: Local
            loadBalancerIP: 192.168.1.91
        ports:
          web:
            redirectTo:
              port: websecure
              priority: 10
