apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: -1
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 41.0.2

    # External Names set for gitea
    chart: traefik
    helm:
      valuesObject:
        accessLog:
          enabled: true
          addInternals: true
        providers:
          kubernetesCRD:
            allowExternalNameServices: true
        service:
          single: false
          annotations:
            metallb.universe.tf/allow-shared-ip: "traefik-shared-ip"
          spec:
            externalTrafficPolicy: Local
            loadBalancerIP: 192.168.1.95
        ports:
          web:
            http:
              redirections:
                entryPoint:
                  to: websecure
                  scheme: https
                  permanent: true
          websecure:
            http3:
              enabled: true
              advertisedPort: 443
            forwardedHeaders:
              insecure: false # Automatically strips fake headers from untrusted external clients
            http:
              middlewares:
                # Needs the @kubernetescrd to locate the resource apparently
                - kube-system-hsts-headers@kubernetescrd
