---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sonarr
  namespace: vpn
spec:
  hosts:
  - "sonarr.tuckerthomas.com"
  gateways:
  - istio-ingress/vpn-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8989
        host: sonarr.vpn.svc.cluster.local