apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: apps

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.k8s.tuckerthomas.com`)
      kind: Rule
      services:
        - kind: Service
          name: sonarr
          namespace: apps
          port: 8989

  tls:
    secretName: apps-cert-prod
    domains:
      - main: sonarr.k8s.tuckerthomas.com
