---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-cert-prod
  namespace: apps
spec:
  secretName: apps-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "tuckerthomas.com:"
    - "*.tuckerthomas.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io