---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: public-cert-prod
  namespace: public
spec:
  secretName: public-cert-prod
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "*.tuckerthomas.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io