---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vpn-apps-cert-prod
  namespace: vpn
spec:
  secretName: vpn-apps-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - "adguard.tuckerthomas.com"
    - "prowlarr.tuckerthomas.com"
    - "radarr.tuckerthomas.com"
    - "sonarr.tuckerthomas.com"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: vpn-apps-cert-staging
#  namespace: istio-ingress
#spec:
#  secretName: vpn-apps-cert-staging
#  duration: 2160h # 90d
#  renewBefore: 360h # 15d
#  isCA: false
#  privateKey:
#    algorithm: RSA
#    encoding: PKCS1
#    size: 2048
#  usages:
#    - server auth
#    - client auth
#  dnsNames:
#    - "adguard.tuckerthomas.com"
#    - "prowlarr.tuckerthomas.com"
#    - "sonarr.tuckerthomas.com"
#  issuerRef:
#    name: letsencrypt-staging
#    kind: ClusterIssuer
#    group: cert-manager.io
#