apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  sources:
  - repoURL: oci://quay.io/cilium/charts/cilium
    targetRevision: 1.19.1
    chart: cilium
    helm:
      valueFiles:
      - $rainbow/values.yaml
  - repoURL: http://cyan.rainbow.tuckerthomas.com:4000/tuckerthomas/rainbow
    targetRevision: argo
    path: clusters/rainbow/core/cilium
    ref: rainbow

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true