# Disabling due to issue with rpi4
# https://github.com/envoyproxy/envoy/issues/23339
l7Proxy: false
ingressController:
  enabled: false
gatewayAPI:
  enabled: false

# Explicitly enable ipv6
ipv4:
  enabled: true
ipv6:
  enabled: true

ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/network/concepts/ipam/
  mode: "cluster-pool"
  operator:
    # @schema
    # type: [array, string]
    # @schema
    # -- IPv4 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv4PodCIDRList: ["10.1.0.0/16"]
    # -- IPv4 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv4MaskSize: 24
    # @schema
    # type: [array, string]
    # @schema
    # -- IPv6 CIDR list range to delegate to individual nodes for IPAM.
    clusterPoolIPv6PodCIDRList: ["fd12:3456:1::/56"]
    # -- IPv6 CIDR mask size to delegate to individual nodes for IPAM.
    clusterPoolIPv6MaskSize: 64

hostFirewall:
  # -- Enables the enforcement of host policies in the eBPF datapath.
  enabled: true

encryption:
  # -- Enable transparent network encryption.
  enabled: true
  # -- Enable Node to Node encryption
  nodeEncryption: true
  # -- Encryption method. Can be one of ipsec, wireguard or ztunnel.
  type: wireguard
  