---
apiVersion: v1
kind: Pod
metadata:
  name: anubis
  namespace: kube-system # Pod is a namespaced a resource
spec:
  containers:
    - name: anubis
      image: ghcr.io/techarohq/anubis:latest
      imagePullPolicy: Always
      env:
        - name: "BIND"
          value: ":8080"
        - name: "DIFFICULTY"
          value: "4"
        - name: ED25519_PRIVATE_KEY_HEX
          valueFrom:
            secretKeyRef:
              name: anubis-key
              key: ED25519_PRIVATE_KEY_HEX
        - name: "METRICS_BIND"
          value: ":9090"
        - name: "SERVE_ROBOTS_TXT"
          value: "true"
        - name: "TARGET"
          value: "http://localhost:5000"
        - name: "OG_PASSTHROUGH"
          value: "true"
        - name: "OG_EXPIRY_TIME"
          value: "24h"
      resources:
        limits:
          cpu: 750m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: kube-system # Service is a namespaced resource
spec:
  type: ClusterIP
  selector:
    app: anubis
  ports:
    - port: 8080 # port that will be externally exposed on the load balancer
      targetPort: 8080 # pod's port for internal routing

---
# Forward authentication to example.com
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: anubis-auth
  namespace: public
spec:
  forwardAuth:
    address: http://anubis.kube-system.svc.cluster.local:8080/.within.website/x/cmd/anubis/api/check
    trustForwardHeader: true