---
apiVersion: v1
kind: Pod
metadata:
  name: anubis
  namespace: kube-system # Pod is a namespaced a resource
  labels:
    # For service selector
    app: anubis
spec:
  containers:
    - name: anubis
      image: ghcr.io/techarohq/anubis:latest
      imagePullPolicy: Always
      env:
        - name: "BIND"
          value: ":8080"
        - name: "DIFFICULTY"
          value: "4"
        - name: ED25519_PRIVATE_KEY_HEX
          valueFrom:
            secretKeyRef:
              name: anubis-key
              key: ED25519_PRIVATE_KEY_HEX
        - name: "METRICS_BIND"
          value: ":9090"
        - name: "SERVE_ROBOTS_TXT"
          value: "true"
        - name: "TARGET"
          value: " "
        - name: "OG_PASSTHROUGH"
          value: "true"
        - name: "OG_EXPIRY_TIME"
          value: "24h"
        # Specifies which domains Anubis is allowed to redirect to.
        - name: "REDIRECT_DOMAINS"
          value: "tuckerthomas.com"
        # Should be the full external URL for Anubis (including scheme)
        - name: "PUBLIC_URL"
          value: "https://anubis.tuckerthomas.com"
        # Should match your domain for proper cookie scoping
        - name: "COOKIE_DOMAIN"
          value: "tuckerthomas.com"
      resources:
        limits:
          cpu: 750m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 256Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault