apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard-home
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts  # Can point to either a Helm chart repo or a git repo.
    targetRevision: HEAD  # For Helm, this refers to the chart version.

    # helm specific config
    chart: adguard-home  # Set this when pulling directly from a Helm repo. DO NOT set for git-hosted Helm charts.
    helm:
      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: apps