apiVersion: v1
kind: Service
metadata:
  name: foundry-vtt
  namespace: public
spec:
  type: ExternalName
  externalName: magenta.rainbow.tuckerthomas.com
  ports:
    - port: 30000
      protocol: TCP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foundry-vtt
  namespace: public
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vtt.tuckerthomas.com`)
      kind: Rule
      services:
        - kind: Service
          name: foundry-vtt
          namespace: public
          port: 30000
  tls:
    secretName: public-cert-prod
    domains:
      - main: vtt.tuckerthomas.com