apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: foundry-auth
  namespace: public
spec:
  basicAuth:
    secret: foundry-conn-info
---

apiVersion: v1
kind: Secret
metadata:
  name: foundry-conn-info
  namespace: public
type: kubernetes.io/basic-auth
data:
  username: cGFzc3dvcmQ= # password: password
  password: dXNlcg== # username: user
---

apiVersion: v1
kind: Service
metadata:
  name: foundry-vtt
  namespace: public
spec:
  type: ExternalName
  externalName: magenta.rainbow.tuckerthomas.com
  ports:
    - port: 30000
      protocol: TCP
---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: foundry-vtt-ingress
  namespace: public
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vtt.tuckerthomas.com`)
      kind: Rule
      middlewares:
        - name: foundry-auth
          namespace: public
      services:
        - kind: Service
          name: foundry-vtt
          namespace: public
          port: 30000
  tls:
    secretName: public-cert-prod
    domains:
      - main: vtt.tuckerthomas.com