---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
  namespace: kube-system
spec:
  addresses:
  - 192.168.1.90-192.168.1.100

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: local-pool-advertisement
  namespace: kube-system
spec:
  ipAddressPools:
  - local-pool