---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - istio.yaml
  - jetstack.yaml
  - k8s-at-home-charts.yaml
  - kiali.yaml
  - metallb.yaml
  - nfs-subdir-external-provisioner.yaml
  - prometheus-community.yaml