---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: vpn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-pink
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi