---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: vpn
spec:
  chart:
    spec:
      chart: transmission
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      version: 8.3.1
  interval: 1m0s
  values:
    env:
      TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
      TRANSMISSION_RPC_PASSWORD: password
      TRANSMISSION_RPC_USERNAME: admin
      TRANSMISSION_WATCH_DIR: /watch
      TRANSMISSION_WATCH_DIR_ENABLED: false
      TRANSMISSION_WEB_HOME: /web
      TZ: UTC
    image:
      pullPolicy: IfNotPresent
      repository: ghcr.io/k8s-at-home/transmission
      tag: v3.00
    ingress:
      main:
        enabled: false
    initContainers:
      update-volume-permission:
        command:
        - sh
        - -c
        - chown -R 568:568 /config
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /config
          name: config
    persistence:
      config:
        enabled: true
        existingClaim: transmission-config-pvc
      downloads:
        enabled: true
        mountPath: /downloads
        type: custom
        volumeSpec:
          nfs:
            path: /volume1/Media/downloads
            server: 192.168.1.10
      watch:
        enabled: false
        mountPath: /watch
    probes:
      liveness:
        spec:
          timeoutSeconds: 30
      readiness:
        spec:
          timeoutSeconds: 30
    service:
      main:
        ports:
          http:
            port: 9091
            targetPort: 9091
        type: NodePort
      utptcp:
        enabled: true
        ports:
          utptcp:
            enabled: true
            port: 55545
            protocol: TCP
            targetPort: 55545
        type: ClusterIP
      utpudp:
        enabled: true
        ports:
          utpudp:
            enabled: true
            port: 55545
            protocol: UDP
            targetPort: 55545
        type: ClusterIP

