apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 8.3.1

    chart: transmission
    helm:
      values: |
        nodeSelector:
          lan: 1Gi
        
        hostname: transmission
        env:
          PUID: 1038
          PGID: 65538
          TZ: UTC
          USER: admin
          PASS: iBEvFQGJchLhzHHKdr3WwhqjaTB9
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/linuxserver/transmission
          tag: 4.0.1-r0-ls159
        ingress:
          main:
            enabled: false
        initContainers:
          update-volume-permission:
            command:
              - sh
              - -c
              - chown -R 1038:1038 /config
            image: busybox
            securityContext:
              runAsUser: 0
            volumeMounts:
              - mountPath: /config
                name: config
        persistence:
          config:
            enabled: true
            existingClaim: transmission-config
          downloads:
            enabled: true
            mountPath: /downloads
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/downloads
                server: 192.168.1.10
          watch:
            enabled: false
            mountPath: /watch
        probes:
          liveness:
            spec:
              timeoutSeconds: 30
          readiness:
            spec:
              timeoutSeconds: 30
        service:
          main:
            ports:
              http:
                port: 9091
                targetPort: 9091
            type: NodePort
          utptcp:
            enabled: true
            ports:
              utptcp:
                enabled: true
                port: 56670
                protocol: TCP
                targetPort: 56670
            type: ClusterIP
          utpudp:
            enabled: true
            ports:
              utpudp:
                enabled: true
                port: 56670
                protocol: UDP
                targetPort: 56670
            type: ClusterIP
