apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 8.3.1

    chart: transmission
    helm:
      values: |
        nodeSelector:
          lan: 1Gi
        
        hostname: transmission
        env:
          #TRANSMISSION_DOWNLOAD_DIR: /media/downloads/complete
          #TRANSMISSION_INCOMPLETE_DIR: /media/downloads/incomplete
          #TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
          #TRANSMISSION_RPC_PASSWORD: password
          #TRANSMISSION_RPC_USERNAME: admin
          #TRANSMISSION_WATCH_DIR: /watch
          #TRANSMISSION_WATCH_DIR_ENABLED: false
          #TRANSMISSION_WEB_HOME: /web
          #TRANSMISSION_PEER_LIMIT_GLOBAL: 1000
          #TRANSMISSION_PEER_LIMIT_PER_TORRENT: 200
          #TRANSMISSION_SPEED_LIMIT_UP: 3000
          #TRANSMISSION_SPEED_LIMIT_UP_ENABLED: true
          #TRANSMISSION_PEER_PORT: 55545
          #TRANSMISSION_RATIO_LIMIT: 3
          #TRANSMISSION_RATIO_LIMIT_ENABLED: false
          #TZ: UTC
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/linuxserver/transmission
          tag: 4.0.1
        ingress:
          main:
            enabled: false
        initContainers:
          update-volume-permission:
            command:
              - sh
              - -c
              - chown -R 568:568 /config
            image: busybox
            securityContext:
              runAsUser: 0
            volumeMounts:
              - mountPath: /config
                name: config
        persistence:
          config:
            enabled: true
            existingClaim: transmission-config
          downloads:
            enabled: true
            mountPath: /downloads
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/downloads
                server: 192.168.1.10
          watch:
            enabled: false
            mountPath: /watch
        probes:
          liveness:
            spec:
              timeoutSeconds: 30
          readiness:
            spec:
              timeoutSeconds: 30
        service:
          main:
            ports:
              http:
                port: 9091
                targetPort: 9091
            type: NodePort
          utptcp:
            enabled: true
            ports:
              utptcp:
                enabled: true
                port: 56688
                protocol: TCP
                targetPort: 56688
            type: ClusterIP
          utpudp:
            enabled: true
            ports:
              utpudp:
                enabled: true
                port: 56688
                protocol: UDP
                targetPort: 56688
            type: ClusterIP
