---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- traefik-ingress.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.1/manifests/install.yaml

patches:
  - path: overlays/production/argocd-cmd-params-cm.yaml
