apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
    - ServerSideApply=true

  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: system-monitoring

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.13.1
  
    chart: kube-prometheus-stack
    helm:
      valuesObject:
        namespaceOverride: "system-monitoring"
        alertmanager.ingress:
          enabled: true
          path: /
          hosts:
            - alertmanager.k8s.tuckerthomas.com
          annotations:
            kubernetes.io/ingress.class: traefik
          labels: {}
        grafana.ingress:
          enabled: true
          path: /
          hosts:
            - grafana.k8s.tuckerthomas.com
          annotations:
            kubernetes.io/ingress.class: traefik
          labels: {}
        prometheus.ingress:
          enabled: true
          path: /
          hosts:
            - prometheus.k8s.tuckerthomas.com
          annotations:
            kubernetes.io/ingress.class: traefik
          labels: {}
