apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deluge
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 5.4.2

    chart: deluge
    helm:
      values: |
        nodeSelector:
          lan: 1Gi

        hostname: deluge
        env:
          PUID: 568
          PGID: 568
          DELUG_LOGLEVEL: error
          TZ: UTC
        image:
          pullPolicy: IfNotPresent
          repository: linuxserver/deluge
          tag: 2.1.1
        ingress:
          main:
            enabled: false
        initContainers:
        #  update-volume-permission:
        #    command:
        #      - sh
        #      - -c
        #      - chown -R 568:568 /config
        #    image: busybox
        #    securityContext:
        #      runAsUser: 0
        #    volumeMounts:
        #      - mountPath: /config
        #        name: config
          update-secret-permissions:
            command: ["/bin/sh"]
            args:
              - -c
              - >-
                rm /config/core.conf &&
                rm /config/auth &&
                echo "Copying secrets to correct locations" &&
                cp /secrets/core.conf /config/core.conf &&
                cp /secrets/auth /config/auth &&
                echo "Updating Permissions on files" &&
                chmod 750 /config/core.conf &&
                chmod 750 /config/auth &&
                echo "Updating file owner " &&
                chown -R 568:568 /config/core.conf &&
                chown -R 568:568 /config/auth &&
                echo "Secret permissions set"
            image: busybox
            securityContext:
              runAsUser: 0
            volumeMounts:
              - name: config
                mountPath: /config
              - name: config
                mountPath: /secrets/core.conf
                subPath: core.conf
              - name: auth
                mountPath: /secrets/auth
                subPath: auth
        persistence:
          config:
            enabled: true
            existingClaim: deluge-config
            mountPath: /config
          config-core:
            enabled: true
            type: secret
            name: deluge-core-config-sealed
            mountPath: /secrets/core.conf
            subPath: core.conf
            defaultMode: 0755
          auth:
            enabled: true
            type: secret
            name: deluge-auth-sealed
            mountPath: /secrets/auth
            subPath: auth
            defaultMode: 0755
          downloads:
            enabled: true
            mountPath: /downloads
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/downloads
                server: 192.168.1.10
          watch:
            enabled: false
            mountPath: /watch
        probes:
          liveness:
            spec:
              timeoutSeconds: 30
          readiness:
            spec:
              timeoutSeconds: 30
        service:
          main:
            ports:
              http:
                port: 58846
                targetPort: 58846
            type: NodePort
          web:
            enabled: true
            ports:
              web:
                enabled: true
                port: 8112
                protocol: TCP
                targetPort: 8112
            type: ClusterIP
          utptcp:
            enabled: true
            ports:
              utptcp:
                enabled: true
                port: 56688
                protocol: TCP
                targetPort: 56688
            type: ClusterIP
          utpudp:
            enabled: true
            ports:
              utpudp:
                enabled: true
                port: 56688
                protocol: UDP
                targetPort: 56688
            type: ClusterIP
