apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deluge
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 5.4.2

    chart: deluge
    helm:
      valueFiles:
        - values.yaml
