apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deluge
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 5.4.2

    chart: deluge
    helm:
      values: |
        nodeSelector:
          lan: 1Gi

        hostname: deluge
        env:
          PUID: 568
          PGID: 568
          DELUG_LOGLEVEL: error
          TZ: UTC
        image:
          pullPolicy: IfNotPresent
          repository: linuxserver/deluge
          tag: 2.1.1
        ingress:
          main:
            enabled: false
        #initContainers:
        #  update-volume-permission:
        #    command:
        #      - sh
        #      - -c
        #      - chown -R 568:568 /config
        #    image: busybox
        #    securityContext:
        #      runAsUser: 0
        #    volumeMounts:
        #      - mountPath: /config
        #        name: config
        #  update-volume-permission:
        #    command:
        #      - sh
        #      - -c
        #      - chown -R 568:568 /config/core.conf
        #      - chown -R 568:568 /config/auth
        #    image: busybox
        #    securityContext:
        #      runAsUser: 0
        #    volumeMounts:
        #      - mountPath: /config 
        #        name: config
        persistence:
          config:
            enabled: true
            type: secret
            name: deluge-core-config-sealed
            mountPath: /config/core.conf
            subPath: core.conf
            defaultMode: 420
          config-extras:
            enabled: true
            existingClaim: deluge-config
            mountPath: /config
          auth:
            enabled: true
            type: secret
            name: deluge-auth-sealed
            mountPath: /config/auth
            subPath: auth
            defaultMode: 420
          downloads:
            enabled: true
            mountPath: /media/downloads
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/downloads
                server: 192.168.1.10
          watch:
            enabled: false
            mountPath: /watch
        probes:
          liveness:
            spec:
              timeoutSeconds: 30
          readiness:
            spec:
              timeoutSeconds: 30
        service:
          main:
            ports:
              http:
                port: 58846
                targetPort: 58846
            type: NodePort
          web:
            enabled: true
            ports:
              web:
                enabled: true
                port: 8112
                protocol: TCP
                targetPort: 8112
            type: ClusterIP
          utptcp:
            enabled: true
            ports:
              utptcp:
                enabled: true
                port: 56688
                protocol: TCP
                targetPort: 56688
            type: ClusterIP
          utpudp:
            enabled: true
            ports:
              utpudp:
                enabled: true
                port: 56688
                protocol: UDP
                targetPort: 56688
            type: ClusterIP
