apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: core
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd

spec:
  project: default

  source:
    repoURL: http://192.168.1.49:4000/tuckerthomas/rainbow-flux
    targetRevision: argo
    path: clusters/rainbow/core

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: false
