---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    nfs.io/storage-path: radarr
  name: radarr-config
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-pink
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi