---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-pink-new
  volumeName: pv-rainbow-nfs
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi