apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: vpn

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 16.3.2

    chart: radarr
    helm:
      values: |
        env:
          TZ: UTC
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/onedr0p/radarr-develop
          tag: 4.4.0.6882
        securityContext:
          runAsUser: 1038
          runAsGroup: 65538
        ingress:
          main:
            enabled: false
        initContainers:
          update-volume-permission:
            command:
            - sh
            - -c
            - chown -R 1038:65538 /config
            image: busybox
            securityContext:
              runAsUser: 0
            volumeMounts:
            - mountPath: /config
              name: config
        metrics:
          enabled: false
          exporter:
            env:
              additionalMetrics: false
              port: 9794
              unknownQueueItems: false
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/onedr0p/exportarr
              tag: v1.0.0
          prometheusRule:
            enabled: false
            labels: {}
            rules: []
          serviceMonitor:
            interval: 3m
            labels: {}
            scrapeTimeout: 1m
        persistence:
          config:
            #enabled: true
            #existingClaim: radarr-config
            enabled: true
            type: pvc
            accessMode: ReadWriteOnce
            size: 1Gi
          downloads:
            enabled: true
            mountPath: /downloads
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/downloads
                server: 192.168.1.10
          movies:
            enabled: true
            mountPath: /movies
            type: custom
            volumeSpec:
              nfs:
                path: /volume1/Media/movies
                server: 192.168.1.10
        service:
          main:
            ports:
              http:
                port: 7878
                targetPort: 7878
            type: NodePort
        
        