apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: apps

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.k8s.tuckerthomas.com`)
      kind: Rule
      services:
        - kind: Service
          name: radarr
          namespace: apps
          port: 7878

  tls:
    secretName: apps-cert-prod
    domains:
      - main: radarr.k8s.tuckerthomas.com
