apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tigera-operator
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: tigera-operator

  source:
    repoURL: https://projectcalico.docs.tigera.io/charts
    targetRevision: 3.25.0

    chart: tigera-operator
        
