apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: apps
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd

spec:
  project: default

  source:
    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
    targetRevision: argo
    path: clusters/rainbow/apps

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: false
      selfHeal: true

#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#
#metadata:
#  name: adguard-home
#  # You'll usually want to add your resources to the argocd namespace.
#  namespace: argocd
#
#spec:
#  project: default
#
#  source:
#    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
#    targetRevision: argo
#    path: clusters/rainbow/apps/adguard-home
#
#  destination:
#    server: https://kubernetes.default.svc
#
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true
#
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#
#metadata:
#  name: prowlarr
#  # You'll usually want to add your resources to the argocd namespace.
#  namespace: argocd
#
#spec:
#  project: default
#
#  source:
#    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
#    targetRevision: argo
#    path: clusters/rainbow/apps/prowlarr
#
#  destination:
#    server: https://kubernetes.default.svc
#
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true
#
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#
#metadata:
#  name: sonarr
#  # You'll usually want to add your resources to the argocd namespace.
#  namespace: argocd
#
#spec:
#  project: default
#
#  source:
#    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
#    targetRevision: argo
#    path: clusters/rainbow/apps/sonarr
#
#  destination:
#    server: https://kubernetes.default.svc
#
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true
#
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#
#metadata:
#  name: transmission
#  # You'll usually want to add your resources to the argocd namespace.
#  namespace: argocd
#
#spec:
#  project: default
#
#  source:
#    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
#    targetRevision: argo
#    path: clusters/rainbow/apps/transmission
#
#  destination:
#    server: https://kubernetes.default.svc
#
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true
#
#---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#
#metadata:
#  name: pod-gateway
#  # You'll usually want to add your resources to the argocd namespace.
#  namespace: argocd
#
#spec:
#  project: default
#
#  source:
#    repoURL: http://192.168.1.60:4000/tuckerthomas/rainbow-flux
#    targetRevision: argo
#    path: clusters/rainbow/apps/vpn/pod-gateway
#
#  destination:
#    server: https://kubernetes.default.svc
#
#  syncPolicy:
#    automated:
#      prune: false
#      selfHeal: true