apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: argocd

resources:
  - adguard-home
  - deluge
  - prowlarr
  - radarr
  - sonarr
  - transmission
  - vpn/pod-gateway