apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: argocd

resources:
  - adguard-home/adguard-home.yaml
  - prowlarr/prowlarr.yaml
  - radarr/radarr.yaml
  - sonarr/sonarr.yaml
  - transmission/transmission.yaml
  - vpn/pod-gateway/pod-gateway.yaml