---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: kiali
spec:
  chart:
    spec:
      chart: kiali-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
      version: 1.52.0
  interval: 1m0s
  values:
    cr:
      create: true
      namespace: istio-system
