---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - matrix-dendrite.yaml
  - matrix-hookshot.yaml
  - traefik-ingress.yaml

configMapGenerator:
  - name: hookshot-registration-cm
    namespace: apps
    options:
      disableNameSuffixHash: true
    files:
      - hookshot-registration.yaml
