apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-dendrite
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  source:
    repoURL: https://matrix-org.github.io/dendrite/
    targetRevision: 0.13.7 # For Helm, this refers to the chart version.

    chart: dendrite

    helm:
      valuesObject:
        extraVolumes:
          - name: hookshot-config-vlm
            configMap:
              # Provide the name of the ConfigMap containing the files you want
              # to add to the container
              name: hookshot-registration-cm

        # -- Configure additional mount points volumes in the Dendrite Pod
        extraVolumeMounts:
          - name: hookshot-config-vlm
            mountPath: /data/appservice-config
            

        postgresql:
          enabled: true # this installs Postgres
          primary:
            persistence:
              size: 1Gi # defines the size for $PGDATA

        dendrite_config:
          global:
            server_name: "matrix.k8s.tuckerthomas.com"
            disable_federation: true

          client_api:
            registration_shared_secret: "matrix.k8s.tuckerthomas.com"
          
          app_service_api:
            # -- Disable the validation of TLS certificates of appservices. This is
            # not recommended in production since it may allow appservice traffic
            # to be sent to an insecure endpoint.
            disable_tls_validation: false
            # -- Appservice config files to load on startup. (**NOTE**: This is overriden by Helm, if a folder `./appservices/` exists)
            config_files:
              - /data/appservice-config/hookshot-registration.yaml
