apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.7.3

    chart: sealed-secrets
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller
        
