#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-staging
#spec:
#  acme:
#    email: acme@tuckerthomas.com
#    preferredChain: ""
#    privateKeySecretRef:
#      name: letsencrypt-staging
#    server: https://acme-staging-v02.api.letsencrypt.org/directory
#    solvers:
#      - selector: {}
#        dns01:
#          cloudflare:
#            apiTokenSecretRef:
#              key: api-token
#              name: cloudflare-api-token-secret
#            email: acme@tuckerthomas.com

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: acme@tuckerthomas.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector: {}
        dns01:
          cloudflare:
            apiTokenSecretRef:
              key: api-token
              name: cloudflare-api-token-secret
            email: acme@tuckerthomas.com