---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
  labels:
    app: "" # Unset default app selector label
    istio: gateway # override default istio selector label
spec:
  chart:
    spec:
      chart: gateway
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.14.1
  interval: 1m0s

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vpn-gateway
  namespace: istio-ingress
spec:
  selector:
    app: istio-ingress
    istio: ingress # istio gateway chart default value
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: vpn-apps-cert-staging
    hosts:
    - "*.tuckerthomas.com"
