---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
spec:
  chart:
    spec:
      chart: istio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
      version: 1.14.1
  interval: 1m0s