apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-gateway
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: pod-gateway

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 5.6.2

    # helm specific config
    chart: pod-gateway
    helm:
      values: |
        image:
          repository: ghcr.io/k8s-at-home/pod-gateway
          tag: v1.7.0
        routed_namespaces:
          - vpn
        publicPorts:
          - hostname: transmission # hostname assigned to the pod
            IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
            ports:
              - type: udp
                port: 55545
              - type: tcp
                port: 55545
        settings:
          NOT_ROUTED_TO_GATEWAY_CIDRS: 10.42.0.0/16 10.43.0.0/16 192.168.0.0/16
          VPN_BLOCK_OTHER_TRAFFIC: true
          VPN_INTERFACE: wg0
          VPN_LOCAL_CIDRS: 10.42.0.0/16 10.43.0.0/16 192.168.0.0/16
          VPN_TRAFFIC_PORT: 51820
        updateStrategy: Recreate
        addons:
          vpn:
            configFileSecret: wireguard-config
            enabled: true
            env:
              IPTABLES_BACKEND: nft
              KILLSWITCH: false
            networkPolicy:
              egress:
                - ports:
                    - port: 51820
                      protocol: UDP
                  to:
                    - ipBlock:
                        cidr: 0.0.0.0/0
                - to:
                    - ipBlock:
                        cidr: 10.0.0.0/8
                - to:
                    - ipBlock:
                        cidr: 192.168.0.0/16
              enabled: true
            resources:
              limits:
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
            type: wireguard
            wireguard:
              image:
                repository: ghcr.io/k8s-at-home/wireguard
                tag: v1.0.20210914