apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-gateway
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: pod-gateway

  source:
    repoURL: https://angelnu.github.io/helm-charts
    targetRevision: 6.0.0

    # helm specific config
    chart: pod-gateway
    helm:
      values: |
        image:
          repository: ghcr.io/angelnu/pod-gateway
          tag: v1.8.1
        nodeSelector:
          lan: 1Gi
        routed_namespaces:
          - vpn
        publicPorts:
          - hostname: transmission # hostname assigned to the pod
            IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
            ports:
              - type: udp
                port: 56670
              - type: tcp
                port: 56670
        settings:
          NOT_ROUTED_TO_GATEWAY_CIDRS: 10.0.0.0/8 192.168.0.0/16
          IPTABLES_NFT: "yes"
          VPN_BLOCK_OTHER_TRAFFIC: true
          VPN_INTERFACE: wg0
          VPN_LOCAL_CIDRS: 10.0.0.0/8 192.168.0.0/16
          VPN_TRAFFIC_PORT: 51820
        updateStrategy: Recreate
        addons:
          vpn:
            enabled: true
            type: gluetun
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest
            securityContext:
              capabilities:
                add: ["NET_ADMIN"]
            env:
              - name: VPN_SERVICE_PROVIDER
                value: mullvad
              - name: VPN_TYPE
                value: wireguard
              - name: VPN_INTERFACE
                value: wg0
              - name: FIREWALL
                value: "off"
              - name: DNS_ADDRESS
                value: 1.1.1.1
              - name: DOT
                value: "off"
              - name: SERVER_CITIES
                value: Chicago IL
              - name: SERVER_HOSTNAMES
                value: us231-wireguard
              - name: HTTP_PROXY
                value: 'on'
              - name: LOG_LEVEL
                value: debug
            envFrom:
              - secretRef:
                  name: mullvad-secret
            networkPolicy:
              egress:
                - ports:
                    - port: 51820
                      protocol: UDP
                  to:
                    - ipBlock:
                        cidr: 0.0.0.0/0
                - to:
                    - ipBlock:
                        cidr: 10.0.0.0/8
                - to:
                    - ipBlock:
                        cidr: 192.168.0.0/16
              enabled: true