---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC6FCw03OEA6xAt9tkAk9Pj1hObn99p8Gzu+38JFVzH2nM5RIC23iWXzK5lDg48dAAvaM2T02H/GAgygIZw1y4UFXOGWIMkUWZk7YA0AThF1I3d/K+XnZEDcs5jJHX+jalFwq2kN6BlePsiZM1upNqy4qWs9m1onSt12hxiia9Cg6S8IaZt7usbLGR2puoZELKRFjjoPrjI9Fgeh5OvqeSdMv1F+GbFjx7cv4FEA9I+qZVgsnM4yFx6Pa/0IC3CjRONhLaJ2B4JYJ8f4eZ8z999SgObfWFtOhhsGglEZSNeWqpNLam1b/zMe8W+Ul7AC6H6ZUJ8MJXo2Jqfap44CCLoJN9e5bBaOmjt3gX5ccy+5FYp+tpL1azSmIZR6bpf1ot3s738vjJdm2t+G9ysBXei99mqbl74Uml1IESyCvy18oansHNvthiKnEYLDyoqBFA++etX8qXkbFLV6W3Zr++ImVjQsE5bogK5aGU9yENQVe1njPsyWdYMBAal+Vn9ajFcxkrYdTJOj95vkSP75tfEYhDLdl98+skZrsCpW4rS9bopOc+ehyzJ1YHqYEak76SnmeF5Yyz9v6MgTGDiyJCLXdjG1uTIsPawhDX6pVi40Z4pMIzvwGAfv+VLVwiXSTcG7wfxwSpafdxjHgeoZG40xh7Sg3qMaXusYtPEi8xhTmrBEIo8bwn4GfjyazOlIN0TOTIAjYNLAdCUn4A1tjH9Rf9pq0INpGZCqjL2gQ+aa9MgFrdCN0zBfQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
