---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAO5WNxYblClBSJHKV/YzRb/+eJxGQCK2mUBTTLMp4q8LnCGvnzMZEbHYrxkU3DHUkE6c0XG1cUJ4h+RwuGeKd+nTb2dulHVcpDjqniu9igeXVLEy409F0b/bG5GeO+2s+OQob6aqbW2TzZ8VvA/cPA188CsODL/eJYA+1OV08DFoLzz95LUffgr2ZVfXlQCunvSVNrqhBhk/A9zXq5XA6f33iLrZ2j/Wn4rth6nTTSO1hdy2krEmQiHEntKADkAO5OALHGtyoZgPab0VjiZmKmUWC9VRH2kqQuzl1uZqnSoAPXIjIWqyDDlc+YCUW/m3S1MRXq+K8AaTwN5zZVfekQt+rK+xvxerkrKmsngVIStYA5aPEhRpnJ7sO5S7HbseJokOaOzqmyJXXjZ2XFz2dMbUmMP8fHxAneIB3wSy1R+xfSb8WyOx9xMt2eumoVRFeGuOKaANChvWZPH/6iUQPHLepmo5H4hm0nWbZHWDynHcQV0LEz3RE9j9NK8bz7RxCuonH6rT0UZmteg7e9sjINRgZR3gWuD1XnHcknlmQT5QlNz0UJ5jMpk5lFNiRbh8J+KCqyiZ6UFsBdVSQRd3NzbdaDaxZCzzCDokFs/ojGf9N986USc8nlnFaQE1F3Hvag/8CT3Uto+v35TS1AO+LOI0uRZAUGeKd4/7OJ4qlf191eGm9RZv5+v7MRKuuLgNkLpTkcz76iKOpMBe9aHX0nXvqPZuOrkMMkAHLripfLtvaSzDctXdwyVA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
