---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAk6ipJctToNOmIGphngzaHGjf+9I5bmaQvS1teBJTClEwR8i8HgMifmv85h8n5pU5FAvh2LOfdra5/87UKbNl/01DXycVrvB9ybmS0QEXToXBTGwfR4zOWQeQqvARXQBjfvFPVK+/LejiCZyRSc58e1JA2S9KlO6nul2GHqBxyjsEk3Ld9UH11iTryGSVohsBr6d1ZXXMbTq7ghyG0yNXW0P0IF1CmM+ttkQwo/W+IOVHqpN81ByX5gPHY4jLAsLtkbDNioCb1MW7PQPZRxNrX+tauZttRXJzaIXkffMTQQWLipOFjfyIPZQbAa0ZecGvEbetqyL04CTK6DMgflzpiuPw6gPeSsbnXHPgZqNK71Z+HWOBKZKc7yxjLI3iQmbehePCOM6knJBhxF1wnRvUI8FrzggQk5UB/dTPTr6aWTsBZggtbMnHmufFLMEfmg/SB3yA4a/mBz9MiZv7oIw/mso35ql0nSa6NNRVUwP/Tgpdj0mL5+ODnHgo3utansolAI10QN3r3OIYhWB5zjWCOVVvWoChD2tzMPahwwykigJHi9T7A396ZZX6Fko1JZ3LDmMYn+BfVB5WTSV/sCxfnnFlc5ux+f1B/szMJgy49+wAPQtUMLt/K2VjqOAhu0Wrmo6UyuIdeflcS7vhAdoLXqiLrsKHKxCLVPGKte7MG4/heqs/T7goFnVGENM90nLRq0abupoG5yN9L/OYf72ZU4f3TTk24SCVL+SN4oVCVSiFz8BZFA/va7Q==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
