type: postgresql
mode: standalone
version:
  postgresql: "18"
cluster:
  instances: 1
backups:
  enabled: false
databases:
  - name: sonarr-main              # -- Name of the database to be created.
    ensure: present                # -- Ensure the PostgreSQL database is present or absent - defaults to "present".
    owner: app                     # -- Owner of the database, defaults to the value of the `name` key.
    template: template1            # -- Maps to the TEMPLATE parameter.
    encoding: UTF8                 # -- Maps to the ENCODING parameter.
    connectionLimit: -1            # -- Maps to the CONNECTION LIMIT parameter. -1 (the default) means no limit.
    tablespace: ""                 # -- Maps to the TABLESPACE parameter and ALTER DATABASE.
    databaseReclaimPolicy: retain  # -- One of: retain / delete (retain by default).
    schemas: []                    # -- List of schemas to be created in the database.
     # - name: myschema
     #   owner: app                # -- Owner of the schema, defaults to the database owner.
     #   ensure: present           # -- Ensure the PostgreSQL schema is present or absent - defaults to "present".
    extensions: []                 # -- List of extensions to be created in the database.
     # - name: pg_search
     #   ensure: present           # -- Ensure the PostgreSQL extension is present or absent - defaults to "present".
     #   version: "0.15.21"        # -- Version of the extension to be installed, if not specified the latest version will be used.
     #   schema: ""                # -- Schema where the extension will be installed, if not specified the extensions or current default object creation schema will be used.
    isTemplate: false              # -- Maps to the IS_TEMPLATE parameter. If true, the database is considered a template for new databases.
    locale: ""                     # -- Maps to the LC_COLLATE and LC_CTYPE parameters
    localeProvider: ""             # -- Maps to the LOCALE_PROVIDER parameter. Available from PostgreSQL 16.
    localeCollate: ""              # -- Maps to the LC_COLLATE parameter
    localeCType: ""                # -- Maps to the LC_CTYPE parameter
    icuLocale: ""                  # -- Maps to the ICU_LOCALE parameter. Available from PostgreSQL 15.
    icuRules: ""                   # -- Maps to the ICU_RULES parameter. Available from PostgreSQL 16.
    builtinLocale: ""              # -- Maps to the BUILTIN_LOCALE parameter. Available from PostgreSQL 17.
    collationVersion: ""           # -- Maps to the COLLATION_VERSION parameter.
  
  - name: sonarr-log               # -- Name of the database to be created.
    ensure: present                # -- Ensure the PostgreSQL database is present or absent - defaults to "present".
    owner: app                     # -- Owner of the database, defaults to the value of the `name` key.
    template: template1            # -- Maps to the TEMPLATE parameter.
    encoding: UTF8                 # -- Maps to the ENCODING parameter.
    connectionLimit: -1            # -- Maps to the CONNECTION LIMIT parameter. -1 (the default) means no limit.
    tablespace: ""                 # -- Maps to the TABLESPACE parameter and ALTER DATABASE.
    databaseReclaimPolicy: retain  # -- One of: retain / delete (retain by default).
    schemas: []                    # -- List of schemas to be created in the database.
     # - name: myschema
     #   owner: app                # -- Owner of the schema, defaults to the database owner.
     #   ensure: present           # -- Ensure the PostgreSQL schema is present or absent - defaults to "present".
    extensions: []                 # -- List of extensions to be created in the database.
     # - name: pg_search
     #   ensure: present           # -- Ensure the PostgreSQL extension is present or absent - defaults to "present".
     #   version: "0.15.21"        # -- Version of the extension to be installed, if not specified the latest version will be used.
     #   schema: ""                # -- Schema where the extension will be installed, if not specified the extensions or current default object creation schema will be used.
    isTemplate: false              # -- Maps to the IS_TEMPLATE parameter. If true, the database is considered a template for new databases.
    locale: ""                     # -- Maps to the LC_COLLATE and LC_CTYPE parameters
    localeProvider: ""             # -- Maps to the LOCALE_PROVIDER parameter. Available from PostgreSQL 16.
    localeCollate: ""              # -- Maps to the LC_COLLATE parameter
    localeCType: ""                # -- Maps to the LC_CTYPE parameter
    icuLocale: ""                  # -- Maps to the ICU_LOCALE parameter. Available from PostgreSQL 15.
    icuRules: ""                   # -- Maps to the ICU_RULES parameter. Available from PostgreSQL 16.
    builtinLocale: ""              # -- Maps to the BUILTIN_LOCALE parameter. Available from PostgreSQL 17.
    collationVersion: ""           # -- Maps to the COLLATION_VERSION parameter.
