---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config-pvc
  namespace: vpn
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-pink
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi