---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prowlarr
  namespace: vpn
spec:
  hosts:
  - "prowlarr.tuckerthomas.local"
  gateways:
  - vpn-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 9696
        host: prowlarr.vpn.svc.cluster.local