apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: prowlarr=ghcr.io/linuxserver/prowlarr:nightly
    argocd-image-updater.argoproj.io/prowlarr.platforms: linux/arm64,linux/amd64
    argocd-image-updater.argoproj.io/prowlarr.update-strategy: digest
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: apps

  source:
    repoURL: https://k8s-at-home.com/charts
    targetRevision: 4.5.2

    chart: prowlarr
    helm:
      valuesObject:
        env:
          PUID: 1038
          PGID: 65538
          TZ: UTC
        image:
          pullPolicy: IfNotPresent
          repository: ghcr.io/linuxserver/prowlarr
          tag: develop-1.4.1.3258-ls102
        ingress:
          main:
            enabled: false
        initContainers:
          update-volume-permission:
            command:
            - sh
            - -c
            - chown -R 568:568 /config
            image: busybox
            securityContext:
              runAsUser: 0
            volumeMounts:
            - mountPath: /config
              name: config
        persistence:
          config:
            enabled: true
            existingClaim: prowlarr-config
        service:
          main:
            ports:
              http:
                port: 9696
                targetPort: 9696
            type: NodePort
