---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: apply-cluster-repositories
  path: ./clusters/rainbow/apps
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system