---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: deploy-cluster
  namespace: argocd

resources:
  - apps/apps.yaml
  - core/core.yaml
  - namespaces
  - public/public.yaml
