apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: system-monitoring

  sources:
  - repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.5.7
    chart: alloy-operator
    helm:
      valueFiles:
      - $rainbow/clusters/rainbow/core/alloy-operator/values.yaml
  - repoURL: http://cyan.rainbow.tuckerthomas.com:4000/tuckerthomas/rainbow
    targetRevision: argo
    ref: rainbow
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
